### ISSUE TITLE
Alterar um item do menu

### ISSUE THREAD

**Issue by ftonato** [lcskdc/SangueParaTodos#1]
Sugiro, apenas por legibilidade, que altere o item do menu chamado "Login" para "Acessar/Entrar".
O que acha?

**Comment by lcskdc** [comment]
Obrigado pelo feedback. Vou realizar a alteração acho que vai evitar
questionamento na banca :-)

Abraco.
Em 07/11/2015 16:35, "Ademílson F. Tonato" notifications@github.com
escreveu:

**Comment by ftonato** [comment]
:+1:

**Comment by ftonato** [comment]
Item já resolvido!
