### ISSUE TITLE
Descrição do projeto

### ISSUE THREAD

**Issue by ftonato** [lcskdc/SangueParaTodos#2]
Sugiro que coloque na descrição do projeto ou no README.md a [url](http://sangueparatodos.com.br/) do projeto.
O que acha?

**Comment by ftonato** [comment]
Como isso não vai se concretizar, fecharei a issue, se algum dia achar correto abrir, sinta-se a vontade :)

**Comment by lcskdc** [comment]
Desculpe,

estava atucanado com a documentação. Vou a banca esta semana, assim semana que vem prometo melhorar o readme.md do projeto, afim de indicar melhor os objetivos.

Muito obrigado, e mais uma vez desculpe

**Comment by ftonato** [comment]
:+1:
